---
title: "FrED_SV for paper"
author: "CCD/CSIB CH and EM"
use:    "Contains anlaysis for FrEDI SV for NPD paper"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  rmarkdown::html_document:
    theme: spacelab
    toc: true
    toc_float: true
    toc_depth: 4
editor_options: 
  chunk_output_type: inline
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(tidyverse)
require(FrEDI)

sccPath        <- "." %>% file.path("GitHub/SCC_FrEDI"); sccPath %>% list.files #CH path
tempPath     <- sccPath %>% file.path("data", "input_files"); 
resultsPath     <- sccPath %>% file.path("anlaysis", "graphics_for_paper"); 
```

```{r run FrEDI}
#already formatted to 1986-2005
temp <- read.csv("./data/input_files/temp_baseline/temp_baseline_8653.csv")

#convert from global to conus
temp_C <- temp %>% mutate(temp_C = convertTemps(temp_C_global,from = "global") ) %>% 
  mutate(scenario = "baseline")

pop <- read.csv("./data/input_files/pop/pop_8653.csv") %>% 
  pivot_longer(cols = c("Northern.Plains", "Southern.Plains", "Midwest", "Northeast", "Northwest", "Southeast", "Southwest"),
               names_to = "region",
               values_to = "reg_pop") %>% 
  as_tibble()


run_fredi_sv(sector = "Air Quality - Premature Mortality", 
             driverInput= temp_C, 
             popInput = pop,
             save = TRUE)

run_fredi_sv(sector = "Labor", 
             driverInput= temp_C,
             popInput = pop,
             save = TRUE)

run_fredi_sv(sector= "Air Quality - Childhood Asthma", driverInput = temp_C, popInput = pop, save=TRUE)
```
